name: Update Sync lateast EnjuFolio ğŸŒ³

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 0: Determine which branch to update based on the repo
      - name: Determine Repository Context ğŸ•µï¸â€â™€ï¸
        id: repo-check
        run: |
          if [[ "${{ github.repository }}" == "ZL-Asica/EnjuFolio" ]]; then
            echo "target_branch=portfolio" >> $GITHUB_OUTPUT
          else
            echo "target_branch=main" >> $GITHUB_OUTPUT
          fi

      # Step 1: Checkout target branch ğŸš€
      - name: Checkout target branch ğŸš€
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.repo-check.outputs.target_branch }}

      # Step 2: Clone lateast EnjuFolio template main branch
      - name: Clone lateast EnjuFolio ğŸ“š
        run: |
          git clone --branch main --depth 1 https://github.com/ZL-Asica/EnjuFolio.git EnjuFolio-latest

      # Step 3: Sync content excluding site-specific paths âœ¨
      # If you have additional local-only content, you can continue to add excludes here
      - name: Sync content excluding site-specific paths âœ¨

        run: |
          rsync -av --delete \
            --exclude="/.git/**" \
            --exclude="/src/enju.config.*" \
            --exclude="/src/contents/**" \
            --exclude="/README.md" \
            --exclude="/src/styles/custom.css" \
            --exclude="/public/**" \
            --exclude="/EnjuFolio-latest/**" \
            EnjuFolio-latest/ .
      # Step 4: Clean up temporary directory ğŸ§¹
      - name: Clean up temporary files ğŸ§¹
        run: |
          rm -rf EnjuFolio-latest

      # Step 5: Commit & Push
      - name: Commit and push changes ğŸ“
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git status
          git commit -m "[Bot] âœ¨ Sync from latest EnjuFolio main" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ steps.repo-check.outputs.target_branch }}
